modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"
[[mods]]
modId = "noaddrepcost"
version = "${version}"
displayName = "NoAddRepCost"
logoFile = "icon.png"
description = '''
Removes additional repair costs of items repaired or enchanted in an anvil
'''
[[dependencies.NoAddRepCost]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.NoAddRepCost]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
