
modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]

modId = "noaddrepcost"
version = "${file.jarVersion}"
displayName = "NoAddRepCost"
authors = "Srendi"
description = '''
Removed the additional repair cost of anvils when you merge a lot of items together
'''
[[dependencies.noaddrepcost]]
modId = "forge"
mandatory = true
versionRange = "[43.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.noaddrepcost]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2, 1.20)"
ordering = "NONE"
side = "BOTH"
